language: python
dist: xenial

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
      dist: xenial
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
    wget https://www.python.org/ftp/python/3.3.7/Python-3.3.7.tar.xz;
    tar -xJf Python-3.3.7.tar.xz;
    cd Python-3.3.7;
    ./configure --prefix=/usr/local;
    make;
    sudo make altinstall;
    cd ..;
    fi

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pip install "flask<=1.0.4";
    elif [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
    pip install "flask<=2.0.0";
    else
    pip install flask;
    fi

script:
  - python test.py
