language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3

services:
  - docker

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
    sudo apt-get update;
    sudo apt-get install -y libssl-dev openssl;
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc;
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc;
    echo 'eval "$(pyenv init --path)"' >> ~/.bashrc;
    pyenv install 3.3.7;
    pyenv global 3.3.7;
    fi

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pip install "flask<=1.0.4";
    elif [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
    pip install "flask<=1.1.4";
    else
    pip install flask;
    fi

script:
  - python test.py;
